# Generated by Django 5.2.6 on 2025-10-03 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_enrollment_options_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id')},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='index',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='raw_answers',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Lesson Quiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
