# Generated by Django 5.2.6 on 2025-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_question_options_rename_index_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='raw_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
