# Generated by Django 5.2.6 on 2025-10-22 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_quizattempt_passed_quizattempt_raw_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'index'], name='pages_lesso_module__70d669_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['user', 'lesson'], name='pages_lesso_user_id_e38d18_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'index'], name='pages_modul_course__1f4326_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='lessoncompletion',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_completion'),
        ),
    ]
